# Generated by Django 5.2.7 on 2025-10-29 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_homework_options_homework_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schedule', models.CharField(help_text='e.g., Monday 10:00 AM - 11:00 AM', max_length=200)),
                ('link', models.URLField(help_text='Meeting link (Zoom, Google Meet, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_classes', to='teacher.classsection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Virtual Class',
                'verbose_name_plural': 'Virtual Classes',
                'ordering': ['-created_at'],
            },
        ),
    ]
