# Generated by Django 5.2.7 on 2025-10-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_virtualclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VirtualClass',
        ),
    ]
