[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = [
    'pip install -r requirements_production.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120'
