# Generated by Django 5.1.13 on 2025-10-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='DEEPI EM HIGH SCHOOL', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logo/')),
                ('principal_photo', models.ImageField(blank=True, null=True, upload_to='principal/')),
                ('correspondent_photo', models.ImageField(blank=True, null=True, upload_to='correspondent/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
