# Generated by Django 5.1.13 on 2025-10-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contactinfo_delete_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='management_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
