# Generated by Django 5.1.13 on 2025-10-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_remove_contactinfo_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='correspondent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='correspondent_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='principal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='principal_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='management_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
