# Generated by Django 5.1.13 on 2025-10-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('professional', 'Professional'), ('sports', 'Sports')], max_length=20)),
                ('image', models.ImageField(upload_to='achievements/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highlight', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-created_at'],
            },
        ),
    ]
