# Generated by Django 5.2.7 on 2025-10-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_number']},
        ),
    ]
