# Generated by Django 5.1.13 on 2025-10-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Homework', 'verbose_name_plural': 'Homeworks'},
        ),
        migrations.AddField(
            model_name='homework',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
