# Generated by Django 5.1.13 on 2025-10-19 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_portal', '0001_initial'),
        ('attendance', '0001_initial'),
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='student.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together={('class_name', 'section')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.classsection'),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='attendance.classsection'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'class_section')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('class_section', 'subject', 'student', 'date')},
        ),
    ]
